# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1cf4e1cebc4ee34e34d9ce0896b004436b780db998437a5167bad52412b7f4d9e201262f2dd2409fdf52d79ed0f96ffef46a4cc09805f40e31d57ee32b2598b0

test:
  secret_key_base: 9e63b762d53de68403753afba14bf26f15c9077014a2d8cb3e810d01fc5a481a33c0d56101aa03ad1c74cc80f46ef760450b8494319ffa59e1eda98dd33d2744

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
